spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yum?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
servo:
  pin: 18
  reset:
    time: 1000
  state:
    start: 10
    stop: 0
secret:
  key:
portion:
  default:
    size: 1000
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health, uptime
  endpoint:
    health:
      show-details: always
